### ISSUE TITLE
Typo in quiz for R Basics: Transform Data

### ISSUE THREAD

**Issue by rosemm** [arcus/education_modules#120]
https://liascript.github.io/course/?https://raw.githubusercontent.com/arcus/education_modules/main/r_basics_transform_data/r_basics_transform_data.md#21

Also the image isn't displaying properly for me here: https://liascript.github.io/course/?https://raw.githubusercontent.com/arcus/education_modules/main/r_basics_transform_data/r_basics_transform_data.md#23

**Comment by rosemm** [comment]
@paytonk heads up

**Comment by pm0kjp** [comment]
TYSM!  Fixed with #123
