### ISSUE TITLE
Quizzes not rendering correctly

### ISSUE THREAD

**Issue by leemc-data-ed** [arcus/education_modules#139]
Within the last few days, we've noticed that some quizzes are not rendering correctly. Answers that are supposed to hidden are instead showing up before the user has selected an answer, and asterisks are also showing up on the page. 

Suggested troubleshooting/solution: 

- [x]  Check all module quizzes for incorrect formatting
- [ ] Compare quiz formatting with Liascript example template
- [ ] If necessary, report issue to Liascript

**Comment by rosemm** [comment]
Module  | Date Checked  | Checked By  | Quiz Issues?  |  Notes
--|---|---|---|--
template  | 2022-06-28 12:03pm  | RMH  | y  | Follow up text showing automatically, some (not all) lines of * showing
bash / command line 101  | 2022-06-28 12:06pm  |  RMH | y  | Follow up text showing (Quiz: Why Bash?, one question on Quiz: Editing Files), some * lines
bash / command line 102  | 2022-06-28 12:09pm  |  RMH | y  | Follow up text showing on all quiz questions, some lines of *
creating a git repository  | 2022-06-28 12:11pm  | RMH  | y  | Follow up text showing on all quiz questions, some lines of *
types of data storage models  | 2022-06-28 12:13pm  | RMH  | n  | all quizzes rendering correctly
data visualization in ggplot2  | 2022-06-28 12:14pm  | RMH  | y  | all quiz questions with follow up text are showing it automatically, some lines of *
data visualization in open source software  | 2022-06-28 12:18pm  | RMH  | y  | Follow up text showing on all quiz questions, some lines of *
data visualization in seaborn  | 2022-06028 12:19pm  | RMH  | y  | Follow up text showing on all quiz questions, some lines of *
demystifying python  | 2022-06-28 12:21pm  | RMH  | y  | Follow up text showing on all quiz questions except last one (Quiz: Accessing python on your computer), some lines of *
demystifying sql  | 2022-06-28 12:23pm  | RMH  | y  | One question fine and one entire question not rendering correctly (multiple choice options showing as all one line with `[[]]` between each one, * line, follow up text showing automatically) for Quiz: SQL and Relational Databases; entire question not rendering for Quiz: SQL Tasks
directories and file paths  | 2022-06-28 12:29pm  | RMH  | y  | Follow up text showing on all quiz questions, some lines of *
exploring the history of a git repository  | 2022-06-28 12:30pm  | RMH  | y  | Follow up text showing on all quiz questions, some lines of *. Newlines not showing up correctly in div answer box.
how to troubleshoot  | 2022-06-28 12:32pm  | RMH  | n  | All questions rendering correctly
intro to version control  | 2022-06-28 12:34pm  | RMH  | y | Follow up text showing on the only quiz question, one line of * after follow up text
learning how to learn data science  | 2022-06-28 12:37pm  | RMH  | y  | Third question (of four total) has follow up text showing and both lines of *
missing values in r  | 2022-06-28 12:40pm  | RMH  | y  | Follow up text showing on all quiz questions, some lines of * (also forgot level 1 header for this module, whoops)
omics orientation  | 2022-06-28 12:41pm  | RMH  | y  | Follow up text showing on all quiz questions, some lines of *
python basics: writing python code  | 2022-06-28 12:42pm  | RMH  |  y | Follow up text showing on all quiz questions, some lines of *. I think some whitespace is not rendering correctly in div answer boxes.
r basics: introduction  | 2022-06-28 12:44pm  | RMH  | n  | All questions rendering correctly
r basics: transforming data with dplyr  | 2022-06-28 12:49pm  | RMH  | n   | All questions rendering correctly
r basics: visualizing data with ggplot2  | 2022-06-28 12:51pm  | RMH  | n  | Only one quiz question and it's rendering correctly (albeit with outdated formatting, using html details)
reproducibility  | 2022-06-28 1:38pm  | RMH  | n/a  | no quiz?
reshaping data in r: long and wide data  | 2022-06-28 1:40pm  | RMH  | n  | All questions rendering correctly
setting up git on mac and linux  | 2022-06-28 1:41pm  | RMH  |  y | Follow up text showing on the only quiz question, one line of * after follow up text, whitespace issues in answer div.
setting up git on windows  | 2022-06-28 1:42pm  | RMH  | y  | Follow up text showing on the only quiz question, one line of * after follow up text, whitespace issues in answer div.
sql basics  | 2022-06-28 1:43pm  | RMH  | y  | Follow up text showing for on question of two on Quiz: Comments, WHERE, Null values (no lines of *), all other quiz questions rendering correctly.
sql intermediate  | 2022-06-28 1:46pm  | RMH  | n  | (separate problem with one question, made GH issue for it)
statistical tests  | 2022-06-28 1:50pm  |  RMH |  y | Follow up text showing on all quiz questions, some lines of *.


**Notes:**
For each module, I opened it by copying the lia link from the README and loading it in a fresh incognito window on my personal (non-CHOP) computer (macOS Catalina 10.15.7, 2013 macbook air), which I think has never opened any of these links before.
All times are EST.
