### ISSUE TITLE
Typos In Reproducibility Module

### ISSUE THREAD

**Issue by mkevbrown** [arcus/education_modules#143]
#### 1. Under Before We Get Started
- [ ] After the picture, the first bullet point sentence, ends with _"spell terms and explicitate acronyms"_, but I believe the word is supposed to be _"explicate"._
#### 2. Under Tools For Better Practices
- [ ]  In the first sentence of the subtopic within the parentheses, it has _"(scripts, data management and metdata..)"_ ,  I believe it was meant to be _"data management and metadata"_

**Comment by pm0kjp** [comment]
I actually did mean "explicitate" ... but fixed the second
