### ISSUE TITLE
Typos in Intro to Version Control

### ISSUE THREAD

**Issue by mkevbrown** [arcus/education_modules#147]
#### 1. Under _ "Version Control Systems" _ 
- [x] In the second sentence, the parenthesis is missing after _"commit"_
- [x]  In the text box, spaces missing before the start of each sentence/ at the end of each sentence
- [x] In the last sentence in the text box, there is a space missing between for and multiple.

**Comment by drelliche** [comment]
Additional typos noted in record 76:

> I did notice a typo under the subtopic of version control systems, in the box, there is just a space missing between for and multiple. Additionally, under the same subheading, the parenthesis after commit is missing. For the quiz, I realized the check box was visible for the second question before I was able to see the second question, so it would be nice to just have the checkboxes with the right answer drop-down only after the check mark button is clicked

**Comment by pm0kjp** [comment]
The spacing between paragraphs in our text boxes is off, maybe due to the liascript parsing changes that occurred?
