### ISSUE TITLE
"Typo" for Data Visualization in ggplot2 module

### ISSUE THREAD

**Issue by mkevbrown** [arcus/education_modules#150]
I put "typo" in quotations because I believe it may have been a typo but I am not completely sure. Under “Custom colors for continuous variables”, the first sentence says we will use scale_color_continous() to change the color for a numeric/continuous variable, however in the block of code, scale_color_gradient is used. I believe it may have been a mistake.

**Comment by pm0kjp** [comment]
Hey @rosemm I am adding a label for the ggplot2 module -- I think this refers to the one you wrote, not to the data viz one in R Basics.
