### ISSUE TITLE
Should we add a section called "Is this module right for me?" section to the Overview (see Intro to R and RStudio for example, 3314002)

### ISSUE THREAD

**Issue by leemc-data-ed** [arcus/education_modules#17]

**Comment by pm0kjp** [comment]
@pm0kjp will look into pulling text from YAML into the body of the module.

Proposal: 

* 1 sentence (2 tops!) for "blurb" that goes into YAML.  Very dry, just the facts.
* 2-3 sentence "Is this module right for me" motivational text (maybe in YAML but for sure in module body) that describes what kind of person doing what kind of work will find this helpful.
* 3-5 learning objectives with strong verbs (maybe also in YAML, stay tuned)
* remove extra bonus TOC from front page matter.  It's error prone and annoying to write without giving much if any added value.
* @cgaynor79 will keep her eyes and ears open during catalog UX testing and inform the team as to what kinds of searchable facets / content we might want to consider adding to YAML

**Comment by pm0kjp** [comment]
An aside -- let's consider what we can use to harvest YAML data and create a catalog!  (And then record those steps and share them in an open way, thereby forming the singularity)
