### ISSUE TITLE
Do we want to keep the boxes around code blocks colored or change them to black/white (like inline code).

### ISSUE THREAD

**Issue by leemc-data-ed** [arcus/education_modules#18]

**Comment by pm0kjp** [comment]
I don't have a strong preference... can you attach screenshots in a comment so we can see the difference?  (Honest question, IDK if we can put photos here as I don't see an obvious embed option)

**Comment by pm0kjp** [comment]
Joy will change the css so that:
* for inline code, there is no border, and the font weight is bold.

Aside: we should check out the syntax highlighting for R and improve it, if we have time...

**Comment by rosemm** [comment]
Just in case we want to come back to the syntax hightlighting question, here's how liascript does it currently: https://liascript.github.io/course/?https://raw.githubusercontent.com/LiaScript/docs/master/README.md#41 and https://ace.c9.io/#nav=higlighter
