### ISSUE TITLE
not sure if "Fill" is mentioned before needed in quiz

### ISSUE THREAD

**Issue by leemc-data-ed** [arcus/education_modules#181]
Record ID: 106

One of the exercises uses the "Fill" component, but a user was unsure if that element had been previously discussed in the module.

**Comment by rosemm** [comment]
Hi @pm0kjp I assigned you this one, too, since you're the original author. But again, feel free to pass it along to someone else if you like.

**Comment by drelliche** [comment]
record 32 

The reminders right before the quiz contradict the quiz answers (rephrased user feedback). This may have already been addressed but I can't tell for sure so noting it here

**Comment by franzenr** [comment]
My recollection is that we looked at record 32 and couldn't identify anything contradictory/couldn't figure out what about the reminders didn't meet their needs, but since we never recorded that anywhere, we should definitely take a second look :)

**Comment by pm0kjp** [comment]
Addressed by https://github.com/arcus/education_r_environment/pull/13

**Comment by franzenr** [comment]
@pm0kjp does closing this issue also indicate that record 32 was looked at + decided to not be actionable at this time or some other decision? just wanting to make sure it's explicitly documented :)

**Comment by pm0kjp** [comment]
@franzenr I should have made it clearer -- I did a PR on the education_r_environment repo (https://github.com/arcus/education_r_environment/pull/13) that resolves this!

**Comment by pm0kjp** [comment]
Whoops, hang on, I'm not looking at record 32 explicitly, I was only addressing the top half... I'll check

**Comment by franzenr** [comment]
@pm0kjp did you come to a verdict on that piece? I can also make record 32 into a new issue if that's helpful -- not sure why it was combined here.
