### ISSUE TITLE
help verifying they have the right table of data

### ISSUE THREAD

**Issue by drelliche** [arcus/education_modules#187]
record number 78

User would like a way to verify that they have the correct table of data like the number of rows and head/tail displayed, rather than have to compare the entire table with a screenshot.

**Comment by pm0kjp** [comment]
There isn't any place I can find that depends on learners comparing their results with a screenshot.  We can consider adding some text like "If you did this correctly, you should see results that look something like the following..." followed by a table snippet.  However, SQL is random access and row order is not guaranteed... this is not an enhancement to tackle before Jan. 30

**Comment by pm0kjp** [comment]
update I will add suggested solutions!
