### ISSUE TITLE
Rename folders and files

### ISSUE THREAD

**Issue by franzenr** [arcus/education_modules#193]
All git modules so far (including the [windows setup module](https://github.com/arcus/education_modules/tree/main/git_setup_windows) that complements this mac/linux module) are named "git_*something something something*"

May want to consider updating this module to follow the same naming structure for easier reference/location/linking -- at minimum, perhaps we want both of the setup modules named the same (meaning we could choose instead to adapt the windows module to have similar file and directory naming as this module instead). 

Note that if we update, other modules that link out to this module will need to be updated with the new link.

**Comment by franzenr** [comment]
@drelliche assigning this to you since you wrote the Windows module, and Rose H is of course out on leave

**Comment by drelliche** [comment]
@franzenr This turned out to be pretty quick and easy with a find and replace! Take a look at PR #194
