### ISSUE TITLE
first practice problem is confusing

### ISSUE THREAD

**Issue by franzenr** [arcus/education_modules#212]
record id: 118
learner reports that the first practice problem was confusing, as there were not examples of it in the content, although there were examples of the opposite scenario. 

(editorializing here: I think what they're referring to is the second "quiz", which is the first time we have learners type out a line of code that is checked)

**Comment by franzenr** [comment]
assigning to you @drelliche since I know you co-wrote w Nicole, and seeing as Nicole is either actively on parental leave or getting ready for it, I figured I'd leave her inbox un-cluttered and you can loop in if necessary. (Also, feel free to pass this on to someone else on the team instead if needed!)

**Comment by drelliche** [comment]
Some possibilities for addressing this are:

- add a hint to the question
- add an additional question before this about navigation that does not require the user to navigate up, only down
- wait and see if any other users report similar confusion
- some combination of these options

My instinct is towards adding a hint, but not an additional question.

@franzenr any strong opinions or other suggestions?

**Comment by franzenr** [comment]
I think adding a hint could be a good idea (perhaps something like "Remember, you can use .. to go up one level in your directory structure") 

Another additional thing that might be useful is to add some specific suggestions of things to play around with when we tell them to "Give it a try" on the Navigation Commands page before the quiz. Since there's no specific prompts of what to do, we don't know whether learners will have tried yet to go back up directories, and therefore maybe didn't fully absorb the information on how to do so. 

Maybe something along the lines of "Give it a try! Use cd, ls, and pwd to explore the directories on your computer. Try navigating around some files and folders that you are already familiar with to get comfortable with how they look through the bash shell. A few things you may want to try are: 
* Using `ls` to learn more about what's in your current directory
* Choose a specific nested folder somewhere on your computer (e.g., the location of your most recent manuscript draft) -- challenge yourself to see if you can get there via the command line
* Try moving up and then back down again in your file hierarchy all in one line" 

This way, they're actually practicing these things while they have something they can work with in front of them. 

It may also be useful to combine the "tab completion" information into the same page as the navigation commands so that when they go on to practice, we can also suggest they practice using tab completion. This would also reduce the current wall of text of tab completion information -- instead of explaining so much to them in words, we could have them experiment -- "What happens when you try to tab complete when more than one directory could match the letters you've already typed in (e.g., pressing tab after `cd L` when the current directory holds both `Letters_of_recommendation` and `Lesson_plans` subdirectories)
