### ISSUE TITLE
QA data_viz_in_OSS

### ISSUE THREAD

**Issue by franzenr** [arcus/education_modules#31]
# Module Quality Assurance Report for PR #2 
----
Date: 2022-03-09
Reviewer: Rose Franzen
qa_template_version: 2.0.0
Name of Module: Data Visualization in Open Source Software
Current Liascript URL: https://liascript.github.io/course/?https://raw.githubusercontent.com/arcus/education_modules/data_viz_open_source/data_visualization_in_open_source_software/data_visualization_in_open_source_software.md#1
Current Version of Module (use the latest commit value): ec9b30b77e4bc3cf0a0253619abfc33b9b25d296
# Checklist Reports:

## [Directory structure](how_to.md/#Begin-Writing)
* [x] Folder and file names use lowercase and underscores (no dashes)
* [x] Main module directory folder name is identical to the name of the module content markdown file.
* [x] Images, videos, and other audio-visual assets are saved within a `media` folder within the module directory

## Module Organization
* [x] YAML is at the very top of the file
  * [x] author name
  * [x] email
  * [x] module version number of at least 1.0.0 if first public version or if this is an update then an [appropriately incremented version number](https://github.com/arcus/education_modules/blob/main/versioning_guidelines.md )
  * [x] module_template_version number is up to date with the [current sample module](https://raw.githubusercontent.com/arcus/education_modules/main/a_sample_module_template/a_sample_module_template.md) -- if not, the module should be brought in line with any changes that have occurred to the module template before continuing with QA
  * [x] language
  * [x] narrator
  * [x] comment appropriately filled out
  * [x] long_description appropriately filled out
  * [x] learning_objectives appropriately filled out
  * [x] link to CSS (currently https://chop-dbhi-arcus-education-website-assets.s3.amazonaws.com/css/styles.css)
  * [x] script to Font Awesome kit (currently https://kit.fontawesome.com/83b2343bd4.js)
* [x] Title is the first line after the end of the YAML
  * [x] only level-1 header in the entire document.
* [x] Overview section immediately following Title
  * [x] surrounded in div with class overview
  * [x] Comment is at the top of the Overview, linked from YAML rather than rewritten
  * [x] "Is this module right for me?" contents linked from long_description YAML rather than rewritten
  * [x] "Estimated time to completion" contents linked from estimated_time YAML rather than rewritten
  * [x] Prerequisites listed and do not require learner to have specifically attained those skills through any of our other modules.
  * [x] Learning objectives linked from learning_objectives YAML rather than rewritten
* [x] All sections following Overview have content (no pages with just header and no additional text / media material).
* [x] All quizzes start with a level 2 or 3 header. If there is only one quiz in the module, it is labelled "Quiz", or if there are multiple, each header is structured as "Quiz: label" where "label" is a short (~ 1-2 words) description of the content covered in the question(s). E.g., "Quiz: Scatterplots"
* [x] Educational content ends with a section of additional resources, both ours and outside sources.
* [x] Final section is Feedback.
  * [x] Learning objectives linked from YAML rather than rewritten
  * [x] Feedback link is updated appropriately to automatically fill in the module name when clicked by learner.

## Content

* [x] Complexity of the material covered seems appropriate given prerequisites.
* [x] Time estimate appears accurate for a learner of the targeted level.
* [x] Clearly defined learning objectives using strong, descriptive verbs. (See [Bloom's taxonomy](https://cft.vanderbilt.edu/guides-sub-pages/blooms-taxonomy/) for ideas.)
* [x] Every learning objective is covered in the module content.
* [x] All major topics covered are represented by a learning objective -- there's no significant knowledge imparted that isn't specified in the learning objectives
* [x] The module title, blurb/comment, and long description accurately reflect the content of the module.
* [x] Headers are informative and follow a sensible hierarchical structure (the TOC in the left margin should give a good overview of the content covered)
* [x] Avoids unclear language: unexplained idioms or references, unexplained acronyms, unnecessary technical language.
* [x] Unusual words, or words taking on a very specific meaning in context, are always defined for the learner, either on the page (e.g. using footnotes) or with links to a definition/glossary.
* [x] Provides pronunciation guides for any especially unusual words of particular importance (a common example is package names, such as dplyr)
* [x] Avoids unnecessarily gendered language (e.g. uses "they" singular rather than "he or she" for an unknown person).
* [x] Informative link text (e.g. instead of "To learn more about python, click [here](www.example.com)", say "Read this article to [learn more about python](www.example.com).")
* [x] Uses specially formatted highlight boxes consistently and appropriately
* [x] Short, digestible pieces --- avoids long paragraphs and breaks long sections up with sub-headers
* [x] All links work (See [Branch References to Change prior to PR Approval](#Branch-References-to-Change-prior-to-PR-Approval) for a place to keep track of internal references that will need to be updated.)
* [x] Spelling and grammar are correct.

## Code availability
If the module includes code that learners may want to run:
* [ NA] A link is provided to run the code in binder
* [NA ] A link to the raw code and any other necessary materials (e.g., data) is provided for learners who prefer to work on their own machine

## Formative assessment

* [x] Sufficient [formative assessment](https://carpentries.github.io/instructor-training/02-practice-learning/#identifying-and-correcting-misconceptions) in the form of quizzes and/or hands-on exercises
* [x] Clear explanations available after questions unless the nature of the question itself or answer options makes it unnecessary (e.g. a T/F question may not always require follow-up explanation)
* [x] Quiz questions and hands-on exercises relate directly to learning objectives
* [x] Every learning objective has at least one associated question
* [x] Questions can be answered based on the content within the module alone; learners should not need to have read or consulted any of the linked external resources

## Videos and images

* [x] Screencasts cover a single coherent task so the recording is a short as is feasible. To demonstrate more than one related task, include several short screencasts in succession rather than recording one long screencast.
* [x] Subtitles available for every recording with audio.
* [x] Alt text is specified for each image. For help writing and assessing descriptive alt text, see this [alt text image concepts guide](https://www.w3.org/WAI/tutorials/images/) and this [alt text decision tree](https://www.w3.org/WAI/tutorials/images/decision-tree/).
  * [x] Alt text never starts with "photo of", "screenshot of", "image of", or any other information describing the medium of the image (the only exception to this is when describing data visualization -- it is appropriate to start alt text with "a scatterplot...", for example)
  * [x] Alt text is written to provide the same relevant information to someone using a screen-reader as provided to someone who accesses the information visually
    - E.g., rather than "Screenshot of PR with multiple commits", alt text says 'On a pull request, the PR comment appears at the top. Below, commits appear as their commit summary followed by commit hash.'
  * [x] For any images that provide a function when clicked, the alt text describes the function of the button rather than describes the visual aspects of the button.
    - E.g., if an image of the GitHub logo is intended to be clicked on to access the education_modules repository, it is labelled "arcus education_modules GitHub repository" rather than "GitHub logo". If this information is also accompanied by a descriptive link in the text, however, then a blank alt tag is appropriate.
  * [x] Alt text is ideally a maximum of 125 characters, or as close to this as possible.
  * [x] Purely [decorative visuals](https://www.w3.org/WAI/tutorials/images/decorative/) ([other examples](https://www.portent.com/blog/design-dev/decorative-images-how-to-identify-and-tag-them-for-accessibility.htm)) have a blank alt text label: `![""](image_path)` Note that this is *not* the same as not specifying alt text at all: `![](image_path)`
* [x] Important visuals (in video, image, or gif) are always described in the audio or in accompanying text.
  - For example, in a screencast, instead of just, "And then click here," provide description that could help scaffold someone without visual access like, "And then click on the button that says 'Run' in the top-right corner of the screen". Be sure to make use of text cues when available (e.g. button labels), not just visual signals like color or location.
  - When important content is conveyed in a visual, describe the key elements. For example, "Running this query produces the table below. It displays the first 5 rows by default, and columns for ID, encounter ID, diagnosis, and outcome."
  - When including a data visualization, describe important features, such as both axis labels and visible trends in the data. For example, "Here's a scatterplot showing number of encounters on the y-axis and age on the x-axis. All 183 patients from our sample are represented here, and it looks like a weak positive trend, with older patients being more likely to have had more encounters. There are a few important outliers, though, such as this patient at about 6 months old with more than 20 encounters already."
  - When visual information is repeated with minimal changes, it's fine to indicate that without providing a full description again. For example, "And here's the updated table, filtered to only show patients who have been seen in the last 2 years."
  - When important visual information in a video is too complex to include sufficient audio description (i.e. it would slow the content down so much as to impair its utility), an alternative video file should be provided with audio descriptions included.
* [x] Color is never the sole method for distinguishing visual content (including in data visualizations).

## Branch References to Change prior to PR Approval

List here any internal references (stated or hyperlinked) that work now because they refer to the named branch, but will not work once this is on the main branch and the named branch is deleted. Prior to approving the PR and merging to main, all references should be updated in a new commit.

(If there are none, the reviewer can either check off the boxes below without making any edits, or can remove the items below and replace with the text "None".)

* [x] {description or quote, line ___ in file ____}
* [x] {description or quote, line ___ in file ____}
* [x] {description or quote, line ___ in file ____}

## Just Before Approval
* [x] Once there are no more commits to be made, get the newest commit value for the PR and update the commit value ("Current Version of Module:") at the top of this document.

Congratulations! You can now approve the PR, merge to main, and close (not delete) this issue.

**Comment by rosemm** [comment]
@franzenr I haven't looked at this module since we started the PR in December, and I know there have been a few updates to the template etc during that time --- let me know if you want me to give it a once over again before you go back to this QA.

**Comment by franzenr** [comment]
@rosemm If you have a chance and don't mind, that would be great, but also I don't mind just flagging those things once I get to them, either way! per Joy I put this one on a bit of a back burner while I focus on a few other things.

One thing I know for sure will need to change given the new updates is the removal of the ToC

**Comment by franzenr** [comment]
updated QR checklist to 2.0.0 version and starting QA process again.

**Comment by franzenr** [comment]
@rosemm 
Something not mentioned in my PR review: 
* the .md file name should be updated to mirror the name of the module directory itself

**Comment by franzenr** [comment]
technically resources linked in additional resources are only to internal resources, but there are countless resources linked throughout the module content itself, so I see that as being more than sufficient to meet that requirement.

**Comment by franzenr** [comment]
@rosemm just sent back again -- a few lingering things but hopefully they're mostly easy enough to just commit my suggestions to fix little things, and after this we should be 100% ready to merge in :)

**Comment by rosemm** [comment]
Okay, thank you for your patience, and for your lovely review. This module has had a long and rocky history, and it definitely showed --- thanks for helping me to pull it together, and sorry it was a bit of a mess! I think it's ready to go now.

**Comment by franzenr** [comment]
@rosemm sent back one last time -- some small formatting stuff, and one of the questions still not rendering properly on my end.

**Comment by rosemm** [comment]
Okie dokie, I think I might have a good version now. I got that quiz question to render properly 🎉 (it was missing a newline between the question and answer options), dropped the LO I wasn't quite addressing, and re-worked the "most true" quiz question that was a bit too sneaky. Let me know what you think! Thanks for your helpful suggestions, @franzenr

**Comment by franzenr** [comment]
Yay, this looks great! 🎉 

It's getting late and my usual eagle eye for spotting typos is not at it's best at this hour, so I'm going to do a once-over again in the morning, but I unless I spy anything new, we'll be all set to merge!

**Comment by franzenr** [comment]
Woohoo 🎉 All done + merged to main! This module has taken quite a journey, thanks for your patience and responsiveness to my many thoughts and questions. @rosemm
