### ISSUE TITLE
Incorrect info in quiz explanation (Database Normalization)

### ISSUE THREAD

**Issue by leemc-data-ed** [arcus/education_modules#317]
In the explantation box for the Normalization quiz (pg. 8) in the Database Normalization module, there is the following text: "This repetition means that it's much easier to correct or change data if we try to put as much data as possible into a single table. However, when a normalized model is used, and data is fragmented into concepts, things get easier. Instead of correcting a product name thousands of times, once for each order that product appears on, we only have to correct it once, in the "product" table."
It seems like the first line should actually say the opposite, that it is much **harder** to correct or change data in a large single table. 
This issue is in reference to feedback record ID 224.

**Comment by pm0kjp** [comment]
Oh yes this is terrible!  LOL fixing now

**Comment by leemc-data-ed** [comment]
Issue addressed by PR #318
