### ISSUE TITLE
no such directory error zsh

### ISSUE THREAD

**Issue by pm0kjp** [arcus/education_modules#350]
Encountered technical difficulties with all of the global path exercises. Even if I was in the correct directory I would receive the "No such file or directory" error. I'm not sure if this is because I'm on macOS Ventura and am running zsh, not bash.

See record 358 in REDCap.

**Comment by drelliche** [comment]
There was not enough information to reproduce this error. If more users report similar problems, hopefully they will include more information or an email so we can reach out for more information.
