### ISSUE TITLE
Arrow key function annoying users

### ISSUE THREAD

**Issue by pm0kjp** [arcus/education_modules#363]
See Records 240, 242 in REDCap.

when I tried to use keyboard arrow keys to move to white space to type, it would skip me to the next, or previous pages instead of letting move around the box. Too cumbersome to write code like that

**Comment by rosemm** [comment]
Another vote for this, record 550. Adding a few key words here, for searchability: arrows, sage, sagemath

**Comment by pm0kjp** [comment]
See also record 996

**Comment by eolivaresb** [comment]
Still no solution for this. I'm use to edit text using ctr+arrows.

**Comment by leemc-data-ed** [comment]
@eolivaresb we agree that this is frustrating! Unfortunately, this is a feature of the software that we use to embed code directly into our modules and how it interfaces with Liascript (the Markdown parser we use to display the modules). We're working on a solution, but that involves testing and implementing a totally different way of embedding interactive code. We hope that this will be solved soon!

**Comment by leemc-data-ed** [comment]
Implementing Pyodide in this module should solve this problem, a link to the relevant PR will be added when it is opened.

**Comment by leemc-data-ed** [comment]
See also record 1901
