### ISSUE TITLE
double check cd commands

### ISSUE THREAD

**Issue by pm0kjp** [arcus/education_modules#364]
I tried a few times to use the cd directory:(file name) and it said it couldn't find the file but later it was written as cd ~/(file name) and that worked just fine. 

see record 230 in REDCap for additional context.

**Comment by drelliche** [comment]
Looking closely at this person's feedback, and comparing it with the other written feedback from that module, (17 total responses, 6 with text, including 230) I'm going to put this issue on ice until/unless we get similar feedback again. I don't think I have enough information here without being able to follow up with the user, who specifies that they had to do additional modifications but doesn't indicate what those modifications were.
