### ISSUE TITLE
consider changing quiz language

### ISSUE THREAD

**Issue by pm0kjp** [arcus/education_modules#368]
3rd quiz question says, "Select all that apply" when there is only one correct answer may not be a best practice for a multiple choice question.  Consider usng radio buttons instead of boxes for multiple choice questions.

See REDCap record 185 for more context

**Comment by drelliche** [comment]
I understand how this could be frustrating as a learner, but if makes learners read all the options and consider each individually whereas a learner would be likely to stop reading after finding the correct answer if they know there is only one correct answer.
