### ISSUE TITLE
Update QA to not require up-to-date docs version? 

### ISSUE THREAD

**Issue by franzenr** [arcus/education_modules#454]
this is a question that arose in conversation between the Roses shortly before launch, in the process of QA for Demystifying LLMs. 

It's unclear whether it makes sense to continue to require that the docs_version for a new module be completely up-to-date with the current version of docs, or if we should revise the QA standards to only require it to be up-to-date with the newest major version. 

Communication copied below to make it easier to pick back up once things settle down 

Rose F: 
> am I correct in my understanding that the only [changes that have occurred to docs](https://github.com/arcus/education_modules/commits/main/docs.md) since 1.0.0 are only relevant for genomics, git, or SQL? And therefore there’s nothing special I need to do to ensure that Joy’s Demystifying LLMs module meets 1.2.1 criteria (other than the normal QA stuff), and can just update the docs_version: to 1.2.1? (currently listed as 1.0.0)?

Rose H: 
> Yep! The idea with the issue templates is that we’ll have one for any major updates to docs, but it’s probably not worth it to create (or update) issue templates for the kinds of things that count as minor revisions

Rose F: 
> Makes sense! The QA criteria require that for new modules, though, they are up to date with whatever the current version is, so I just wanted to make sure I wasn’t missing anything there :slightly_smiling_face: But yeah creating a new issue template for each minor (or revision) seems like a lot! 

Rose H:
> So for LLM, you could leave that at 1.0.0, and that would be fine (we wouldn’t bother formally updating it until we hit docs v2 anyway), or you could bump it up to 1.2.1, since, as you point out, there are no meaningful changes for LMM between 1.0.0 and 1.2.1 

Rose F: 
> do we want to update the QA criteria then, to mirror that? Right now it’s worded to suggest that new modules must be up to date with the current docs version number. 
> I could see where it might be valuable to have that requirement stay, though. For example, if this was a SQL module, we might want to make sure it has the most up-to-date SQL macros, right? (I’m not actually sure how important that is, though)  

Rose H: 
> maybe pop it in an issue? and we can return to it in a few weeks

**Comment by rosemm** [comment]
QA checklist actually doesn't explicitly require docs_version to match current (maybe that changed at some point since this convo?). Closing this issue now since it's no longer a problem.
