### ISSUE TITLE
Excel PowerQuery and PowerBI

### ISSUE THREAD

**Issue by drelliche** [arcus/education_modules#483]
record number: 447

Description of issue: Learner suggests that we mention that queries in Excel are scripted even though cell formulas are not.

**Comment by rosemm** [comment]
Just double checking the use of the urgent label here? @drelliche

**Comment by drelliche** [comment]
I might have been over-interpreting their comment, but if this is incorrect information (particularly information that turns off new learners that do scripted queries in Excel), I'd like to get it fixed ASAP, even if it is just a comment that it is possible to do scripted queries even if that isn't the most common use of Excel... But I'm also open to pushback on the urgent label.

**Comment by rosemm** [comment]
Gotcha! That makes perfect sense, thank you. I agree we should get a fix on this ASAP.
