### ISSUE TITLE
Incorrect instructions for downloading dataset in Practice modules

### ISSUE THREAD

**Issue by leemc-data-ed** [arcus/education_modules#488]
The UC Irvine ML repository has been updated, and so the instructions for downloading the cervical cancer dataset in Python Practice and R Practice need to be updated ASAP.

**Comment by rosemm** [comment]
I don't quite have time to do this now before I have to sign off for the day, but popping the updated link to the dataset here for anyone else that starts it: http://archive.ics.uci.edu/dataset/383/cervical+cancer+risk+factors 
If no one else grabs it, I should be able to do this first thing tomorrow morning!

**Comment by leemc-data-ed** [comment]
I'm happy to do it for both modules, shouldn't take me more than a few minutes! The link actually still works, but the button we're pointing folks to on the page itself is different now.

**Comment by rosemm** [comment]
It looks like we should also update the general link to http://archive.ics.uci.edu/ (http://archive.ics.uci.edu/ml/index.php is giving me a 404 error)

**Comment by leemc-data-ed** [comment]
Oh yeah good call, I didn't check the general one (the one directly to the data still works luckily)
