### ISSUE TITLE
QA Template

### ISSUE THREAD

**Issue by franzenr** [arcus/education_modules#50]
To create a new QA issue, copy and paste the text of the [quality assurance template](https://github.com/arcus/education_modules/blob/main/quality_assurance_template.md) into the description of a new issue. 

Further instructions on setting up a quality assurance issue can be found in this [QA how-to guide](https://github.com/arcus/education_modules/blob/main/quality_assurance_guide.md)

**Comment by rosemm** [comment]
Updated process: To start a QA issue, click the `New Issue` button and select the template for the type of module you're assessing.
