### ISSUE TITLE
`man` command does not work in Git Bash

### ISSUE THREAD

**Issue by rosemm** [arcus/education_modules#501]
record number: 551

Description of issue: `man` command does not work in Git Bash, we should note that for Windows users

**Comment by drelliche** [comment]
We had some other comments about this last wave and updated the module, but perhaps it needs to be even more emphasized? I think this is worth noting if we get more of this feedback, to maybe change the format of that section to make it clearer what applies to which users.

**Comment by leemc-data-ed** [comment]
I think we can probably remove the "urgent" label, but good feedback to keep track of if it might be confusing to folks.

**Comment by drelliche** [comment]
Since we seem to have gotten through wave 2 without additional comments to this, I'm going to close it as being sufficiently addressed by the existing information in the highlight box.
