### ISSUE TITLE
Quiz question only accepts double quotes as correct, should allow single quotes as well

### ISSUE THREAD

**Issue by rosemm** [arcus/education_modules#508]
record number: 585, 670

Description of issue: Entered the correct answer in a quiz, but the module marked it wrong because we were looking for double quotes rather than single. Learner was already familiar with python and so new enough to try changing the quotes, but this could be very frustrating for a learner coming in with less experience. This is also an accessibility issue (single quotes are more accessible than double quotes).

**Comment by leemc-data-ed** [comment]
Neither Elizabeth nor I were able to get this to work, but there is a "Hint" in that quiz that tells you to use double quotes. A quick solution might be to bring that hint out so that everyone can see it (and not just folks who reveal the hint).

**Comment by leemc-data-ed** [comment]
Given the accessibility concern, we should make an effort to get this to work.

**Comment by leemc-data-ed** [comment]
Another vote for this one: record 805
