### ISSUE TITLE
module templates need added front matter

### ISSUE THREAD

**Issue by franzenr** [arcus/education_modules#517]
If my understanding of the [docs](https://github.com/arcus/education_modules/blob/main/docs.md) is correct, then we need to add: 
* good_first_module
* sets_you_up_for
* depends_on_knowledge_available_in

to the front matter that is included in the [templates](https://github.com/arcus/education_modules/tree/main/_module_templates) for all 3 module types. 

Presumably all exercise module types will need to have both of the following (and therefore it should be added to the front matter in the templates. 
* coding_level 
* coding_language

**Comment by franzenr** [comment]
@rosemm @drelliche does this seem correct? :)

**Comment by rosemm** [comment]
Yes, your understanding is right! 
I'm also down to make `coding_required` a required field. I think that might be a "major" change to docs, though. The versioning for docs and templates is not as well spelled out as it is for modules, but it means we would need to go back over all the modules that were updated to docs v1 and check them for that field.

**Comment by drelliche** [comment]
I agree with all of these proposals, and think `coding_required` as a required field makes a lot of sense.

**Comment by rosemm** [comment]
I split off a separate issue for making coding_required a mandatory field, but the missing front matter stuff is now fixed in PR 524
