### ISSUE TITLE
non-public link

### ISSUE THREAD

**Issue by franzenr** [arcus/education_modules#519]
record number: 718

Description of issue: learner unable to access enterprise github link. 

This link should not be in the module -- as part of QA, ALL resources and links must be fully public and relevant to all learners, not just CHOP ones.

**Comment by pm0kjp** [comment]
I don't see any link to enterprise github here?

**Comment by franzenr** [comment]
oops, I forgot to have this one closed with PR #547 -- I removed that link in that update! Thanks for catching and closing this @pm0kjp :)
