### ISSUE TITLE
Charge for AWS is a problem, even if it's small

### ISSUE THREAD

**Issue by rosemm** [arcus/education_modules#560]
record number: 953

Description of issue: Learner skipped this module because of the fee to use AWS. It's not clear whether the amount was a barrier for them or if they just objected to being charged on principle (either would be valid, of course!). They also expressed disappointment that the fact that there might be a charge wasn't made clear before the start of the study.

**Comment by leemc-data-ed** [comment]
Another vote for this: Record 1895
