### ISSUE TITLE
Wrapper module too advanced for a beginner

### ISSUE THREAD

**Issue by pm0kjp** [arcus/education_modules#575]
record number: 845

Description of issue: Getting Started with Docker tutorial assumes too much prior knowledge (Joy adds here: is there a place here for a middle ground module between Demystifying and this tutorial / wrapper?)

**Comment by rosemm** [comment]
Two related issues to think about: 

1. Do the pre_reqs correctly capture the knowledge required to complete the module? 
2. Do we need additional content (a different module) to bring more learners up to speed before completing this one? Would this be in the bash sequence, or something else?
