### ISSUE TITLE
Liascript text sizing not working?

### ISSUE THREAD

**Issue by pm0kjp** [arcus/education_modules#597]
record number: 904

Description of issue: User reports that on Safari, the view type and font / letter size controls were not working for this module.

**Comment by leemc-data-ed** [comment]
I was able to reproduce. In fact, I wasn't able to change any of the settings or the presentation mode.

**Comment by rosemm** [comment]
I just tested this as well and couldn't replicate. Type size, dark mode, etc. all worked fine for me on Safari. Maybe this was a temporary issue?
