### ISSUE TITLE
Unspecified typos

### ISSUE THREAD

**Issue by pm0kjp** [arcus/education_modules#601]
record number: 908

Description of issue: User says there are multiple typos including in code, does not specify where.  Test all code to make sure it is correct!

**Comment by rosemm** [comment]
I scanned for typos in the text itself and didn't find any. Didn't check the code yet (although this is code we've used many times in workshops as well, so it has been thoroughly tested previously).

**Comment by rosemm** [comment]
I also just checked all the code. I can't find any typos, other than two small ones which I fixed (none in the code). I think we'll have to close this for the moment, unless we can get some more specific info.
