### ISSUE TITLE
Pre-running sage cells on data editing page

### ISSUE THREAD

**Issue by drelliche** [arcus/education_modules#647]
record number: 1178, 1435

Description of issue: The module asks learns to edit the dataframe, but because the cells have already run before the learners get to give them a try, the page is extra confusing.
1435 adds: For example, in the replacement exercise for replacing "male" with "M", the gender column is already "M" prior to transformation.

Note: this behavior will hopefully be completely fixed when we upgrade from SageMathCells to Pyodide.

**Comment by rosemm** [comment]
#849 fixed this!
