### ISSUE TITLE
Creating table 1 section obscured

### ISSUE THREAD

**Issue by drelliche** [arcus/education_modules#649]
record number: 1191

Description of issue: User reports that the "creating table 1 with gtsummary" is hard to read and partially obscured by a scroll bar.

**Comment by rosemm** [comment]
This depends on the text display size (which the user controls) and the dimensions of the screen they're looking at, etc. so we can't fix this for all scenarios. 
There were a few lines of code that were very wide, though, so I wrapped those more to help with this.
