### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by drelliche** [arcus/education_modules#653]
record number: 1216, 1517

Description of issue: Karl Broman link is not working.

**Comment by rosemm** [comment]
I checked and the link works fine for me: https://peerj.com/preprints/3183.pdf 
It's on the [additional resources](https://liascript.github.io/course/?https://raw.githubusercontent.com/arcus/education_modules/main/tidy_data/tidy_data.md#15) page of the module.

**Comment by drelliche** [comment]
It works for me too, but it might be worth checking from off of the CHOP network?

**Comment by drelliche** [comment]
We have determined we can't reproduce this.

**Comment by franzenr** [comment]
just checked it off the CHOP network to fully confirm, link worked fine for me.

**Comment by rosemm** [comment]
This link is to a preprint pdf, but that appears to not work some times, very mysteriously. Replace it with the link to the actual peerreviewed article: https://www.tandfonline.com/doi/full/10.1080/00031305.2017.1375989 (which is what we should really be linking to anyway).

**Comment by franzenr** [comment]
Ugh wait, I just realized that this peer-reviewed link is going to be paywalled, which we usually try to avoid where possible. 

Karl Broman has made a [pdf of the paper](https://kbroman.org/Paper_DataOrg/manuscript.pdf) available on his website, which I propose we link to instead  (alternatively, there's an [html version](https://kbroman.org/Paper_DataOrg/manuscript.html), which, while it may look less "official" is likely more accessible to folks using screenreaders, as PDFs can be nightmares if not done carefully.
