### ISSUE TITLE
Quiz question not accepting answers?

### ISSUE THREAD

**Issue by rosemm** [arcus/education_modules#725]
record number: 1556

Description of issue: Learner reports 2nd quiz question regarding adding dictionary value to the dictionary not working or accepting answers. Note that I was unable to replicate this in chrome, but we should test more broadly.

Here's the link: https://liascript.github.io/course/?https://raw.githubusercontent.com/arcus/education_modules/main/python_basics_lists_dictionaries/python_basics_lists_dictionaries.md#7

**Comment by leemc-data-ed** [comment]
I haven't been able to replicate this in Chrome or Safari-- but I did notice another problem. Recently, @rosemm you updated this quiz answer to accept both single and double quotes in PR #637. Single quotes are marked correct, but single quotes give the error `Unexpected identifier 'Angola'. Expected ';' after variable declaration.'
![dictionary_quiz_error](https://github.com/arcus/education_modules/assets/69471812/8b572b34-b05d-43f8-8766-2f775dc545ec)
I have no idea why it's going this... is this something you've seen @rosemm or @drelliche?

**Comment by leemc-data-ed** [comment]
I think I'm actually going to make a new issue and close this one.

**Comment by drelliche** [comment]
I remember coming across exactly this issue in the regex for this (or a similar answer) before... hmmm

**Comment by leemc-data-ed** [comment]
Any guidance you have @drelliche would be appreciated! I've opened #800 for this problem. Closing this as "can't replicate."
