### ISSUE TITLE
Typo in quiz answer

### ISSUE THREAD

**Issue by rosemm** [arcus/education_modules#726]
record number: 1560

Description of issue: The answer div box is incorrect for the second quiz question on https://liascript.github.io/course/?https://raw.githubusercontent.com/arcus/education_modules/main/regular_expressions_boundaries_anchors/regular_expressions_boundaries_anchors.md#13
>The anchor for the start of a string is the dollar sign, or $, symbol

**Comment by jyapujuju** [comment]
is it fixed?

**Comment by rosemm** [comment]
@jyapujuju Yes, it's fixed now! You will likely need to refresh your browser to have the module display the updated version.
