### ISSUE TITLE
Last quiz question too subjective

### ISSUE THREAD

**Issue by drelliche** [arcus/education_modules#739]
record number: 1648

Description of issue: User notes that different journals have different requirements and sometimes it is entirely up to the researcher to apply rigorous practices.

**Comment by drelliche** [comment]
I want to confirm this change with the original author of the module before making a PR. My suggested changes to the answer to the last question are in **bold**:

> Research data management is important for multiple reasons, among which we highlighted three in this question:
> 
> * Research data management helps researchers create higher quality research output.
> * Research data management supports the long-term preservation of data for future use.
> * Funding agencies supporting the research require research data management.
> 
> It's false that publishers don't apply their own standards. **While some publishers were earlier adopters of the most up-to-date data management policies, all p**ublishers have an important role to play in setting high standards for researchers who submit manuscripts for consideration. It's also false that research data management is a new practice. While it's true that RDM has gotten much more attention lately, research data management has been taking place since the first researchers developed the scientific method, and it's changed over time to adapt to new circumstances and requirements.

**Comment by drelliche** [comment]
I reached out to the original author Ene Belleh for her thoughts on this.

**Comment by Ebelleh** [comment]
@drelliche the changes you've suggested are great. Okay to make a PR.
