### ISSUE TITLE
Quiz marking correct answer wrong

### ISSUE THREAD

**Issue by drelliche** [arcus/education_modules#749]
record number: 1684

Description of problem: User reports entering `mydata %>% select(first_name, last_name)` and it being marked wrong despite being the correct answer.

---

**Some things to try first!** 

- If pyodide cells aren't working as expected in Python modules, we may need to update pyodide. 
- If LiaScript macros aren't rendering properly, especially `overview`, check for blank macros defined in the front matter (e.g.`version_history` is a common culprit). You may need to add load bearing white space. 
- If the `feedback` macro isn't working, check that no front matter fields used in the generated REDCap link are missing (e.g. `module_type`).
- Problems with `div`? You may need a newline after the `div` tag and before the `/div` tag. 
- Quiz answer boxes not displaying properly? There cannot be a newline between the last answer option and the beginning of the question followup section. Make sure the `****` surrounding the answer div starts immediately after the last line of the question.

**Comment by rosemm** [comment]
I can't replicate this as stated. I assume there must have been a small difference in how the learner entered it and what was reported. That said, I noticed this question doesn't use regex on the answer, so it's unnecessarily strict. I'll improve the answer handling to allow flexibility on whitespace, etc.
