### ISSUE TITLE
Quiz could be made more challenging

### ISSUE THREAD

**Issue by rosemm** [arcus/education_modules#757]
record number: 1709

Description of issue: Learner thought it would be better to have the last quiz not rely directly on a script that's in the repo (https://github.com/arcus/learning_bash/blob/main/scripts/interactive_count_type.sh), so it's not quite so easy to just look up the answer.

**Comment by drelliche** [comment]
Yes it is easy to look up the answer since this copied directly from the provided shell script `interactive_count_type.sh` but the pedagogical value of this question is to emphasize the commands `echo` and `read`.
