### ISSUE TITLE
Downloadable files don't match module conent

### ISSUE THREAD

**Issue by leemc-data-ed** [arcus/education_modules#793]
Record number: 1896

Description of issue: A learner emailed to report that the [files that users are directed to download as an alternative to using the AMI ](https://figshare.com/articles/dataset/Data_Carpentry_Genomics_beta_2_0/7726454) do not match the content in the Genomics Tools and Methods: Quality Control module text.

**Comment by rosemm** [comment]
In this case, the learner went to look through documentation other than what we linked to in an attempt to do something we explicitly advise against (running the analyses on their own machine), so it's probably counterproductive to add content to the module to assist with this process unless we were to rework all the content to more officially support a "do it on your own machine" option. 
The larger issue here, though, is that we have plenty of learners who don't want AWS as a solution for running this code (see e.g. #560, #620, #750 and #760). I think we need to rethink how we deliver this content, but we don't need a specific response to the issue raised here.
