### ISSUE TITLE
Check for compliance: Command Line 101

### ISSUE THREAD

**Issue by leemc-data-ed** [arcus/education_modules#80]
Checking for compliance with QA template 2.0.0

**Comment by leemc-data-ed** [comment]
@rosemm one of the things I want to update about this module is to make the title and the folder/file names agree. Right now the title of the module is Command Line 101 but the file is called bash_scripting_101... Do you have thoughts about which might be a more accurate description? I think I have a slight preference to change the title to Bash Scripting 101 ("command line" as a term isn't actually used much in the module), but I'm not married to it.

**Comment by franzenr** [comment]
@rosemm @leemc-data-ed one thing I'm curious about is whether we want to amend our QA standard w/r/t naming things -- technically, this module checks all the boxes. The file + folder names are the same -- it's just that the title that the learner sees when the content is rendered is different. 

Even if it technically passes our bar, it totally confuses me to see both command line 101 and bash scripting 101 floating around. 

Currently, there are many modules with different "Titles" than their folder/file names, but it's generally the case that the folder/file names are just shortened/simplified versions of the Title, where here they're entirely different words. What are y'all's thoughts on the best standard to set?

**Comment by leemc-data-ed** [comment]
I think they should be the same or reasonably close! I think it'll minimize confusion.

**Comment by leemc-data-ed** [comment]
Hi @nafeldman! We have an updated module template, and so we're trying to bring modules that have been published up to the new standard. I've made a few of the simple updates already (minor changes to the YAML, changing the names of the quizzes). I also changed the title of the module to match the file names (so now the title is Bash Scripting 101, but we could change it to Command Line 101 if you prefer-- we'd just need to change the file name). 

The one other thing that I think we need to do is add a quiz to correspond with the first learning objective (what is bash and why would I want to learn it). Since that is actually adding content, I wanted to throw this back to you! It would just need to be some kind of quiz question at the end of the "What is the shell? Why would I use it?" section, so that we have an assessment for every learning objective. 

Thanks! And let me know if you don't have the bandwidth, I can try to come up with something if need be :)

**Comment by nafeldman** [comment]
Hi @leemc-data-ed this all looks and sounds good to me. Unfortunately, I'm very overextended right now with the staffing changes on our team and will probably will continue to be for the next 2-3 months, so if you have time to work on this I'd really appreciate it.

**Comment by leemc-data-ed** [comment]
@nafeldman Totally understandable! I can definitely work on this.

**Comment by nafeldman** [comment]
thanks for being understanding!

**Comment by drelliche** [comment]
@leemc-data-ed  I started reviewing this, and ran into an issue with the instructions for Windows users (which unfortunately is going to be a lot of our users...) They need Admin access to turn on developer mode, and they aren't going to have that. 

One thought is that in the Installing Git for windows modules we have them download Git Bash and use that, which didn't require admin access.  I'm going to keep poking around on my virtual Windows machine and see if I can get around this, but Git Bash might be an end run around needing admin access if we can't find another way. 

<img width="792" alt="Screen Shot 2022-05-09 at 1 16 48 PM" src="https://user-images.githubusercontent.com/99294374/167462868-3ff5fdd4-8ba0-4627-bda3-5bd0eb4b5e1f.png">

**Comment by drelliche** [comment]
Following up, WSL is installed on CHOP-owned Windows machines, but might not be accessible to non-admin users.

**Comment by drelliche** [comment]
This issue has been subsumed by https://github.com/arcus/education_modules/issues/114
