### ISSUE TITLE
Quiz not accepting double quotes, giving strange error

### ISSUE THREAD

**Issue by leemc-data-ed** [arcus/education_modules#800]
Recently, @rosemm you updated this quiz answer to accept both single and double quotes in PR #637. Single quotes are marked correct, but double quotes give the error `Unexpected identifier 'Angola'. Expected ';' after variable declaration.`
![dictionary_quiz_error](https://github.com/arcus/education_modules/assets/69471812/8b572b34-b05d-43f8-8766-2f775dc545ec)
I have no idea why it's doing this... is this something you've seen @rosemm or @drelliche?

_Originally posted by @leemc-data-ed in https://github.com/arcus/education_modules/issues/725#issuecomment-1817111868_

**Comment by drelliche** [comment]
I remember coming across exactly this issue in the regex for this (or a similar answer) before... https://github.com/arcus/education_modules/issues/508

But I see we didn't actually solve the problem, just created an always visible hint to get people to enter it correctly :(

**Comment by leemc-data-ed** [comment]
Hmmm I think PR #637 was intended to address this problem directly, and I thought it worked at the time, though it's possible I'm misremembering. In any case there's currently no hint visible or otherwise, so I'll add one as a temporary patch.
