### ISSUE TITLE
Error in Code Challenge 3

### ISSUE THREAD

**Issue by leemc-data-ed** [arcus/education_modules#820]
record number: 1942

Description of issue: Learner reported that they got an error ("Error: Expecting 'data' to have at least 1 row.") when trying to complete Code Challenge 3, even when running the code in the Solutions file.
Note: I wasn't able to replicate this, though I was prompted to install a couple of packages.

**Comment by rosemm** [comment]
I just tested it as well and the solutions file knits without errors. 
My guess is that the learner tried to run just the code at the end without running the commands earlier on, such as those that load the necessary packages (especially `medicaldata` which contains both of the data files for the module). We could add a warning towards the end to make sure you've loaded the libraries, but this module specifically lists "installing and loading packages" as a prereq, and my inclination is not to belabor information they should be coming in with.
I'm closing this issue now, but feel free to reopen if you disagree.
