### ISSUE TITLE
Update module template: Lesson Preparation

### ISSUE THREAD

**Issue by rosemm** [arcus/education_modules#84]
Module template still mentions pangeo binder in Lesson Preparation. I propose we replace that content with two sections, one for typical R setup and one for typical python setup. 

I also think we should consider centralizing the materials (i.e. media, like screenshots) for these sections, so that they don't need to be copied individually into each module's media folder, and so we can update them across the board with one change if needed. I haven't look at the python setup procedure, but for R materials, I propose we add a media folder to the education_r_environment repo and point to that for all the screenshots etc to be used in modules in the Lesson Preparation section. Module-specific media would of course stay in that module's media folder. 

I also think it would be great to use YAML variables for any folders or files that need to get referenced in Lesson Preparation so that we can just blindly copy-paste that whole section from the template and use it unchanged in a new module, just updating the YAML. (For an example, see the new PR for the Data visualization in ggplot2 module, where I tried this out.)

@pm0kjp and @leemc-data-ed in particular, since the two of you have been writing the intro R and intro python modules, respectively.

**Comment by franzenr** [comment]
This was on my list of things to need to update about documentation/infrastructure -- so glad you also saw this and jumped on top of it! :)

**Comment by rosemm** [comment]
This work is underway (see #336 )
