### ISSUE TITLE
Data type in SQL macro templates

### ISSUE THREAD

**Issue by drelliche** [arcus/education_modules#884]
Right now all of the data types in the alaSQL tables in the SQL macros used by the SQL modules and the Arcus Speaker Series are strings.

But in the SQL Intermediate module and webinar, we teach aggregate functions, some of which (SUM and AVG) cannot be usefully demoed using the tables that have only string data.

There are similarly issues with MAX, MIN, and COUNT when the "NA" values are the string "NA" rather than a null value.

This issue is urgent because we are giving the SQL Intermediate talk next week!

**Comment by drelliche** [comment]
[Information on defining column types](https://github.com/AlaSQL/alasql/wiki/Create-Table) in alasql

[Information on NULL](https://github.com/AlaSQL/alasql/wiki/Null) and [undefinied](https://github.com/AlaSQL/alasql/wiki/Undefined) in alasql

**Comment by rosemm** [comment]
Information on date fields: https://github.com/AlaSQL/alasql/wiki/Date (I think we might want to use `DATE` instead of `Date`)
