### ISSUE TITLE
Link to non-existent file

### ISSUE THREAD

**Issue by franzenr** [arcus/education_modules#922]
In our QA issue templates, we attempt to link to the file "how_to.md" at the Begin Writing subheading. We use this link for the ["Directory Structure"](https://github.com/arcus/education_modules/blob/main/_for_authors/write_a_module.md#structure) header of the QA template

However, we don't seem to have a "how_to.md" file any longer. I think perhaps this is one of the files that we broke up into several different files for the _for_authors directory? 

Based on context clues from where the link is, I'm thinking perhaps the [Structure](https://github.com/arcus/education_modules/blob/main/_for_authors/write_a_module.md#structure) section of write_a_module.md might be the best fit, but since I haven't spent much time in these documents lately, its possible there's a better fit elsewhere.

**Comment by rosemm** [comment]
I vote we just remove that link, actually — if we were linking to things that should have been QA requirements, then they should just have been listed in the QA checklist. But if we just put a link in here as like a “if you’re curious, check out more context over here” I think our QA issues aren’t really the right place for that anyway, and just end up contributing to link rot.

**Comment by franzenr** [comment]
sounds like a plan to me!
