### ISSUE TITLE
add field(s) for code "interactivity"

### ISSUE THREAD

**Issue by franzenr** [arcus/education_modules#933]
Based on [docs](https://liascript.github.io/course/?https://raw.githubusercontent.com/arcus/education_modules/main/docs.md#71)\, we consider a module to include "interactive code" if it includes, within the actual pages of the module itself: 

 * "R code examples hosted in binder from [our R notebook repository](https://github.com/arcus/education_r_environment)"
 * "interactive python code in sagemath cells" (note that now it is pyodide cells, not sagemath)
 * "interactive SQL code"

There is currently no way to establish whether a module contains interactive code by looking at the metadata alone -- although there are the `coding_required` and `coding_language` fields, it is possible for a module to instruct learners to run code locally or somewhere other than within binder/cells inside the module. 

There are metadata field requirements that are conditional on whether interactive code is part of the module -- it would be useful to have a programmatic way to identify whether a module contains interactive code to facilitate automated checking of whether those fields are present when necessary. 

There are several ways that we could do this that come to mind, including: 
1. Have a single field: `interactive_code` that is required for all modules for which `coding_required` = true. Acceptable values are true or false. 
      A downside of this approach is that modules could technically have more than one coding language, and I suppose in theory a module could have R that is "interactive" but SQL that is not "interactive" (for ex, maybe they need to write SQL to run a query using bigquery, which they do within the interactive R". We would not be able to correctly ascertain from the value `coding_language` that only the requirements for interactive R need to be present, but not the requirements for interactive SQL. 
2. As an alternative of the above - we could have the same single field: `interactive_code` required under the same circumstances, but instead have acceptable values of R, Python, and/or SQL (any combination is ok). A final acceptable value is N/A, for modules that require code but it is not interactive code.
3. have three separate fields that are required for all modules for which `coding_required` = true : `interactive_python` `interactive_r` and `interactive SQL`. Acceptable values are true or false. 

If this is implemented, this requires updating:

- [ ]  documentation about metadata in [docs](https://github.com/arcus/education_modules/blob/main/docs/index.md)
- [ ] the [exercise module template](https://github.com/arcus/education_modules/blob/main/_module_templates/template_exercise.md) (exercise modules are the only ones for which coding_required is ALWAYS true) 
- [ ] all current modules that include interactive code (as of 2024/05/20 N=15 (python = 5, r = 8, sql = 2))

**Comment by rosemm** [comment]
- To programmatically check for import statement for macros_genomics.md, can search for text "@lesson_prep_ami"
- To programmatically check for import statement for macros_bash.md, can search for text "@lesson_prep_bash_basics"

Optionally, could also programmatically check for: 
 - macros_regex.md with "@regular_expression_checker_warning"

**Comment by franzenr** [comment]
Oh good point about macros_regex.md, it totally passed by me that it even exists. 

Its not noted anywhere in docs -- do you think we should add it to docs, or since its scoped pretty tightly to our regex modules only, which is a series that I think we've finished, do we think its fine to omit? @rosemm

**Comment by franzenr** [comment]
Results from meeting discussion: 

It was brought to my attention that we can alternatively derive whether there is "interactive code" in our modules by looking for use of the related macros within the body of the module. 

For python: look for `@Pyodide.eval`
For R, look for `@lesson_prep_r`
For SQL, look for `@AlaSQL`. 

We will do this instead of creating new metadata fields.

**Comment by rosemm** [comment]
I vote to not add the regex macro info to docs.md, for the reasons you list.
